### ISSUE TITLE
About *.npy files 

### ISSUE THREAD

**Issue by FriedaSmith** [bagustris/deep_mlp_ser#1]
Hello. Can you provide **feat_ws_3.npy**, **y_egemaps.npy** and **feat_hfs_msp3.npy** files? Or can you providethe their generation code?

**Comment by bagustris** [comment]
Sure! it is in `data` directory now.

**Comment by FriedaSmith** [comment]
Thank you very much.

**Comment by FriedaSmith** [comment]
@bagustris  Hello. I also need the **feat_hfs_gemaps_msp_train.npy**, **feat_hfs_gemaps_msp_test.npy** and **improv_data.csv** files? And can you provide their generation code?

In addition, the module was not found (`ModuleNotFoundError: No module named 'calc_scores'` in from calc_scores import calc_scores)

**Comment by bagustris** [comment]
Sorry for the late reply. The *.npy files are uploaded into `data`. The calc_scores.py files are uploaded in `code`. I am looking for the generation codes for these .npy files (or maybe you can search in my other repositories)>

**Comment by FriedaSmith** [comment]
Thank you for your trouble.
